name = "HCBE"
uuid = "b05247dc-eff2-11ea-1b52-2312df516add"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleHypergraphs = "aa4a32ff-dd5d-5357-90e3-e7a9512f0501"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PyCall = "1.91"
